### ISSUE TITLE
removeAllSpies() fails in Jasmine 2.1.2

### ISSUE THREAD

**Issue by drobtravels** [tommyh/jasmine-react#4]
I am getting the following error when I use a spy

```
TypeError: Cannot read property '__reactAutoBindMap' of undefined
  at Object.jasmineReact.removeAllSpies (http://localhost:8888/__spec__/helpers/jasmine_react.js:86:21)
```

Here is a simple example causing the behavior

```
describe('Call', function(){
  it('does something', function(){
    jasmineReact.spyOnClass(App.Components.Call, 'connect');
  });
});
```

The functionality of the spy works, but the error appears during the removeAllSpies function.  the spyOn method in spyOnClass() only returns a function with no base object property, so it fails when attempting to access spy.baseObj

I'm using Jasmine 2.1.2

**Comment by scvnc** [comment]
I came across the same problem.  Looks like this fork/branch has fixed it. https://github.com/Greenfields/jasmine-react/commit/b7425febb708d56bbc9869cf1a5e399a623deee3

@tommyh can we arrange a pull request? :)

In the mean time, you can try out the Greenfields fork 

```
npm install https://github.com/Greenfields/jasmine-react/archive/jasmine-2.1.tar.gz --save-dev
```

**Comment by tommyh** [comment]
Sure!  Thanks for this.  I will try to merge tonight/tomorrow.

**Comment by tommyh** [comment]
Sorry for the delay, working on this now.  Merging that branch in directly causes build fails, so I'm upgrading the suite to be jasmine 2.0 compatible.

**Comment by tommyh** [comment]
Ignore my previous comment, the branch merged in just fine.  (It was when I upgraded the test suite to jasmine 2, I started to see fails... but that is unrelated to this changeset being valid.)

Merged.  @Greenfields - thanks for the contribution!  @scvnc - sorry for the delay.

**Comment by scvnc** [comment]
Thanks @tommyh !
