### ISSUE TITLE
Stubbing out subcomponents

### ISSUE THREAD

**Issue by azaharakis** [tommyh/jasmine-react#7]
In the readme you have an example of stubbing out a subcomponent, however to do so requires it being declared on the window object. How would you recommend stubbing out subcomponents that are initialized via commonJs syntax? Would you have to use rewire to get to the internals?

**Comment by svileng** [comment]
I was wondering exactly the same @azaharakis. Any ideas @tommyh?

**Comment by tommyh** [comment]
Yes, using something like rewire is exactly what you'd need todo.

The main thing you have to watch out for is to "un-rewire" your module after the test is complete, or else you will get test sanitization issues.  So I'd recommend writing a jasmine helper to make this dry and error proof.

I have a full example of this in an ebook I co-authored: http://shop.oreilly.com/product/mobile/9781939902122.do

I'm just getting back from traveling, so if you give me a day or two I will try to put the relevant portions of the rewire helper on this thread.

**Comment by tommyh** [comment]
Here is an excerpt of the book which covers this topic: http://bleedingedgepress.com/mock-components/

If I get some time I might publish "rewire-jasmine" into a standalone library.

If someone would like to make a pull request adding a relevant portion for rewirify to the README that would be appreciated.  I will close out this issue until either I do it or someone else does.  :)

**Comment by azaharakis** [comment]
Hi Tommy, thanks for the link mate! This is how I've gone about stubbing out my components, but one thing that got me thinking with that methodology is that we are actually replacing the component entirely with a stub that's being made within the test. 
Something I like to do is verify that a subcomponent was called but not care what happens after that. With rewire you are replacing that component entirely, which means that someone could change the logic could do the same, and the test would still pass as it's checking a stubbed module was called and not the intended one.
Any thoughts on this?
